### ISSUE TITLE
Change hard-coded file pattern to modifiable argument

### ISSUE THREAD

**Issue by KristinaUlicna** [lowe-lab-ucl/octopuslite-reader#11]
Currently, `OCTOPUSLITE_FILEPATTERN` in utils.py is hard-coded. It would be nice to have an optional key-worded argument to allow reading images with different file name patterns such as `segmentation_000_mask.tiff` etc. to be changed when calling the `DaskOctopusLiteLoader`

**Comment by quantumjot** [comment]
Sounds like a good plan @KristinaUlicna - do you want to have a go at a PR for this?
