### ISSUE TITLE
Add on-the-fly stack registration

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/octopuslite-reader#4]
@nthndy - would be good to enable *on-the-fly* stack registration using the code from: https://github.com/lowe-lab-ucl/segment-classify-track/blob/main/align.ipynb

we can add it to the transform utils added in PR #3

**Comment by nthndy** [comment]
Need to also remove blank/overexposed frames in this step as current on-the-fly transformation neglects frames that have been previously removed in https://github.com/lowe-lab-ucl/segment-classify-track/blob/main/align.ipynb

**Comment by quantumjot** [comment]
> Need to also remove blank/overexposed frames in this step as current on-the-fly transformation neglects frames that have been previously removed in https://github.com/lowe-lab-ucl/segment-classify-track/blob/main/align.ipynb

This block of code could be used to interpolate the values if you know which frames have been removed:
https://github.com/lowe-lab-ucl/octopuslite-reader/blob/87ecfbc913cee9712d0effd9ed364fb73c012d5d/octopuslite/transform.py#L72-L78
