### ISSUE TITLE
Input transform shape issue

### ISSUE THREAD

**Issue by nthndy** [lowe-lab-ucl/octopuslite-reader#5]
https://github.com/lowe-lab-ucl/octopuslite-reader/blob/87ecfbc913cee9712d0effd9ed364fb73c012d5d/octopuslite/transform.py#L20
@quantumjot 
This line expects an input transformation of `shape (2,)` but if you provide the transform as a path to a .npy file (like I've been using) then the input is a transformation matrix of `shape (3,3)`. Not sure what sort of input arrays you have tried but should I change this line to pull the relevant xy coord shift from this (3,3) array?

**Comment by nthndy** [comment]
i.e. `tform = tf.AffineTransform(translation=self.transforms[idx, :2, 2])` ?

**Comment by quantumjot** [comment]
go ahead and change if you need to!

**Comment by nthndy** [comment]
Need to sort the original on the fly registration first as this solution works but is on a lag of however many previously removed over/under-exposed frames there are

**Comment by nthndy** [comment]
think this was sorted a while back as correct coords are now in the transform reader
