### ISSUE TITLE
postprocessing should not run on certain data types 

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/octopuslite-reader#9]
e.g. `remove_background` should not run on `MASK` or `WEIGHTS`

**Comment by nthndy** [comment]
this should be the case for `parse_transforms` too right?

**Comment by quantumjot** [comment]
> this should be the case for parse_transforms too right?

I guess so, yes!

**Comment by nthndy** [comment]
okay ill give fixing this a go
